### ISSUE TITLE
upload function is given the wrong number of arguments

### ISSUE THREAD

**Issue by gcetusic** [VorskiImagineering/django-C3PO#3]
django-cp3o's reset action calls upload method in c3po.mod.communicator.Communicator with multiple arguments...If we look at the definition of that function it really does accept only one argument:

```
def upload(self):
```

This produces "TypeError at /c3po/ upload() takes exactly 1 argument (4 given)"
when clicking reset.

**Comment by gcetusic** [comment]
Could you push the changes to pypi?

**Comment by nomarek** [comment]
Yes, new version is now available from PyPi.
